# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Raspberry
tagline:          'Xuan Nguyen IOS Blog'
description:      'IOS Development'
url:              http://www.rsbry.com

author:
  name:           'Xuan Nguyen'
  url:            http://www.rsbry.com

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/xuan


pages_list:       
  Support: '/support'
  Blog: '/blog'
  Feed: '/atom.xml'